// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewProduct struct {
	ProductName  string  `json:"product_name" bson:"product_name"`
	ProductPrice float64 `json:"product_price" bson:"product_price"`
	ProductStock int32   `json:"product_stock" bson:"product_stock"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Product struct {
	ProductID    string  `json:"product_id" bson:"_id"`
	ProductName  string  `json:"product_name" bson:"product_name"`
	ProductPrice float64 `json:"product_price" bson:"product_price"`
	ProductStock int32   `json:"product_stock" bson:"product_stock"`
}

type Query struct {
}

type UpdateUser struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	UserID   string `json:"user_id" bson:"_id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
